expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On
error_log = /proc/self/fd/2

memory_limit = 128M
max_execution_time = 30
max_input_time = 30
default_socket_timeout = 30
upload_max_filesize = 30M
post_max_size = 32M

opcache.enable = 1
opcache.memory_consumption = 128
opcache.interned_strings_buffer = 16
opcache.max_accelerated_files = 20000
; Code is replaced by building and recreating containers on every release.
opcache.validate_timestamps = 0
